package mem

import (
	"encoding/json"
	"fmt"
	"strings"
)

// RenderClassicMindMapWorkspace returns a self-contained local application.
// It intentionally uses no remote assets so the editor remains private and
// continues to work without Internet access.
func RenderClassicMindMapWorkspace(sessionToken string) ([]byte, error) {
	bootstrap, err := json.Marshal(map[string]any{
		"session_token": strings.TrimSpace(sessionToken),
		"node_kinds": []map[string]string{
			{"value": "topic", "label": "Тема"}, {"value": "subtopic", "label": "Подтема"},
			{"value": "fact", "label": "Факт"}, {"value": "note", "label": "Заметка"},
			{"value": "quote", "label": "Цитата"}, {"value": "question", "label": "Вопрос"},
			{"value": "task", "label": "Задача"}, {"value": "decision", "label": "Решение"},
			{"value": "link", "label": "Ссылка"},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("encode classic mind map workspace: %w", err)
	}
	page := strings.Replace(classicMindMapWorkspaceHTML, "__MEM_BOOTSTRAP__", string(bootstrap), 1)
	return []byte(page), nil
}

const classicMindMapWorkspaceHTML = `<!doctype html>
<html lang="ru" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>mem · Карты мыслей</title>
<style>
:root{color-scheme:dark;--bg:#090c12;--panel:#10151e;--panel2:#151c28;--line:#293445;--text:#edf3ff;--muted:#8f9bad;--accent:#65d6b4;--accent2:#8c7cff;--warn:#ffc857;--danger:#ff6b7a;--shadow:0 18px 55px rgba(0,0,0,.28);--node:#161e2b;--grid:rgba(255,255,255,.035)}
html[data-theme="light"]{color-scheme:light;--bg:#f4f6fa;--panel:#fff;--panel2:#f7f9fc;--line:#d8deea;--text:#172033;--muted:#657084;--accent:#087f69;--accent2:#6551d8;--warn:#9b6500;--danger:#c83d50;--shadow:0 18px 55px rgba(38,52,74,.14);--node:#fff;--grid:rgba(23,32,51,.045)}
*{box-sizing:border-box}html,body{height:100%;margin:0}body{font:14px/1.45 "Segoe UI",Inter,Arial,sans-serif;background:var(--bg);color:var(--text);overflow:hidden}button,input,textarea,select{font:inherit}button{color:inherit}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.hidden{display:none!important}
.app{height:100%;display:flex;flex-direction:column}.topbar{height:58px;flex:none;display:flex;align-items:center;gap:12px;padding:0 18px;border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--panel) 94%,transparent)}.brand{font-weight:800;letter-spacing:.16em;font-size:13px}.brand span{color:var(--accent)}.spacer{flex:1}.icon-btn,.btn{border:1px solid var(--line);background:var(--panel2);border-radius:8px;padding:8px 12px;cursor:pointer;transition:.16s ease}.icon-btn:hover,.btn:hover{border-color:var(--accent);transform:translateY(-1px)}.btn.primary{background:var(--accent);border-color:var(--accent);color:#07110f;font-weight:700}.btn.danger{border-color:color-mix(in srgb,var(--danger) 55%,var(--line));color:var(--danger)}.btn.ghost{background:transparent}.btn.small{padding:5px 9px;font-size:12px}.btn:disabled{opacity:.45;cursor:not-allowed;transform:none}.field{width:100%;border:1px solid var(--line);background:var(--bg);color:var(--text);border-radius:8px;padding:9px 11px}.field::placeholder{color:var(--muted)}textarea.field{min-height:110px;resize:vertical}.eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--accent);font-weight:700}.muted{color:var(--muted)}
.library{height:100%;overflow:auto;padding:42px max(24px,calc((100vw - 1280px)/2)) 80px;background:radial-gradient(circle at 85% 5%,color-mix(in srgb,var(--accent2) 13%,transparent),transparent 28%),var(--bg)}.hero{display:flex;gap:28px;align-items:end;margin-bottom:28px}.hero-copy{max-width:760px}.hero h1{font-size:clamp(34px,5vw,64px);line-height:1.02;margin:8px 0 12px;letter-spacing:-.04em}.hero p{max-width:650px;color:var(--muted);font-size:16px}.hero-actions{margin-left:auto;display:flex;gap:8px}.library-tools{display:grid;grid-template-columns:minmax(250px,1fr) auto;gap:12px;margin:25px 0}.check{display:flex;gap:8px;align-items:center;color:var(--muted)}.map-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:16px}.map-card{min-height:210px;border:1px solid var(--line);border-radius:12px;background:var(--panel);padding:20px;display:flex;flex-direction:column;box-shadow:var(--shadow);transition:.18s ease}.map-card:hover{border-color:color-mix(in srgb,var(--accent) 55%,var(--line));transform:translateY(-2px)}.map-card.archived{opacity:.68}.map-card h2{font-size:21px;margin:10px 0 8px;line-height:1.2}.map-card p{color:var(--muted);margin:0;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.map-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px;color:var(--muted);font-size:12px}.pill{border:1px solid var(--line);border-radius:999px;padding:3px 8px}.card-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:auto;padding-top:18px}.empty{grid-column:1/-1;border:1px dashed var(--line);border-radius:12px;text-align:center;padding:70px 20px;color:var(--muted)}
.editor{height:100%;display:flex;flex-direction:column}.editor-head{height:58px;flex:none;display:flex;align-items:center;gap:10px;padding:0 12px;border-bottom:1px solid var(--line);background:var(--panel)}.back{font-weight:700}.map-heading{min-width:170px}.map-heading strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:32vw}.map-heading small{color:var(--muted)}.search{width:min(300px,24vw)}.depth{width:130px}.workspace{min-height:0;flex:1;display:grid;grid-template-columns:minmax(0,1fr) 390px}.canvas{position:relative;min-width:0;background-color:var(--bg);background-image:linear-gradient(var(--grid) 1px,transparent 1px),linear-gradient(90deg,var(--grid) 1px,transparent 1px);background-size:28px 28px;overflow:auto}.scene{position:relative;min-width:100%;min-height:100%;width:max-content;padding:80px 110px;transform-origin:0 0}.links{position:absolute;inset:0;pointer-events:none;overflow:visible}.mind-tree{position:relative;display:flex;align-items:center;min-height:calc(100vh - 220px)}.branch{display:flex;align-items:center;gap:86px;position:relative}.children{display:flex;flex-direction:column;gap:18px}.node-shell{position:relative;display:flex;align-items:center}.node{position:relative;width:225px;min-height:66px;text-align:left;border:1px solid color-mix(in srgb,var(--kind,var(--accent2)) 55%,var(--line));border-left:4px solid var(--kind,var(--accent2));border-radius:10px;background:var(--node);padding:10px 34px 10px 12px;box-shadow:0 8px 24px rgba(0,0,0,.16);cursor:pointer;transition:.15s ease}.node:hover{transform:translateY(-1px);border-color:var(--kind,var(--accent2))}.node.selected{outline:2px solid var(--accent);outline-offset:3px}.node.dim{opacity:.24}.node.drop-target{outline:3px solid var(--warn);outline-offset:4px}.node-label{display:block;font-weight:700;line-height:1.25}.node-summary{display:block;color:var(--muted);font-size:12px;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.node-type{display:block;color:var(--kind,var(--accent));font-size:10px;letter-spacing:.1em;text-transform:uppercase;margin-top:7px}.collapse{position:absolute;z-index:2;right:8px;top:9px;width:22px;height:22px;border:1px solid var(--line);border-radius:50%;background:var(--panel2);cursor:pointer;color:var(--muted);padding:0}.collapse:hover{color:var(--text);border-color:var(--accent)}.lock{position:absolute;right:10px;bottom:8px;font-size:11px;color:var(--warn)}.zoom{position:sticky;z-index:5;left:18px;bottom:18px;width:max-content;display:flex;gap:5px;padding:5px;border:1px solid var(--line);border-radius:10px;background:var(--panel);box-shadow:var(--shadow)}.canvas-hint{position:sticky;z-index:4;left:18px;top:18px;width:max-content;max-width:calc(100vw - 470px);padding:7px 10px;border-radius:7px;background:color-mix(in srgb,var(--panel) 88%,transparent);color:var(--muted);font-size:12px}
.inspector{min-width:0;border-left:1px solid var(--line);background:var(--panel);display:flex;flex-direction:column}.inspector-head{padding:18px;border-bottom:1px solid var(--line)}.inspector-head h2{font-size:20px;margin:5px 0 4px}.tabs{display:flex;gap:4px;padding:10px 12px;border-bottom:1px solid var(--line);overflow:auto}.tab{border:0;border-bottom:2px solid transparent;background:transparent;color:var(--muted);padding:7px 9px;cursor:pointer;white-space:nowrap}.tab.active{color:var(--text);border-color:var(--accent)}.tab-pane{min-height:0;overflow:auto;padding:16px 18px}.form-grid{display:grid;gap:12px}.form-grid label{display:grid;gap:5px;color:var(--muted);font-size:12px}.row{display:flex;gap:8px;align-items:center}.row>*{min-width:0}.actions{display:flex;gap:7px;flex-wrap:wrap;padding-top:4px}.section{padding:14px 0;border-top:1px solid var(--line)}.section:first-child{border-top:0;padding-top:0}.source-card,.history-card{border:1px solid var(--line);border-radius:9px;padding:12px;margin-bottom:9px;background:var(--panel2)}.source-card strong,.history-card strong{display:block}.source-card pre{white-space:pre-wrap;font:inherit;color:var(--muted);margin:8px 0 0}.state-current{color:var(--accent)}.state-stale,.state-missing{color:var(--danger)}.welcome{padding:34px 20px;color:var(--muted);text-align:center}.welcome strong{display:block;color:var(--text);font-size:18px;margin-bottom:8px}
dialog{width:min(560px,calc(100vw - 30px));border:1px solid var(--line);border-radius:13px;background:var(--panel);color:var(--text);padding:0;box-shadow:var(--shadow)}dialog::backdrop{background:rgba(0,0,0,.62);backdrop-filter:blur(2px)}.dialog-head{padding:18px 20px;border-bottom:1px solid var(--line)}.dialog-head h2{margin:4px 0}.dialog-body{padding:20px;display:grid;gap:13px}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;padding:15px 20px;border-top:1px solid var(--line)}.toast{position:fixed;z-index:20;left:50%;bottom:24px;transform:translate(-50%,20px);padding:10px 14px;border:1px solid var(--line);border-radius:9px;background:var(--panel);box-shadow:var(--shadow);opacity:0;pointer-events:none;transition:.18s}.toast.show{opacity:1;transform:translate(-50%,0)}.toast.error{border-color:var(--danger);color:var(--danger)}
@media(max-width:900px){body{overflow:auto}.app,.library,.editor{height:auto;min-height:100vh}.workspace{grid-template-columns:1fr}.inspector{border-left:0;border-top:1px solid var(--line);min-height:52vh}.canvas{height:65vh}.editor-head{height:auto;min-height:58px;flex-wrap:wrap;padding:9px;position:sticky;top:0;z-index:10}.search{width:180px}.hero{align-items:flex-start;flex-direction:column}.hero-actions{margin:0}.library{padding:28px 18px 60px}.map-heading strong{max-width:62vw}.canvas-hint{max-width:80vw}}
</style>
</head>
<body>
<div class="app">
  <section id="library" class="library" aria-label="Библиотека карт мыслей">
    <div class="hero"><div class="hero-copy"><div class="eyebrow">MEM · CLASSIC MIND MAPS</div><h1>Мысли складываются<br>в ясную структуру.</h1><p>Каждый запрос или ручной проект живёт отдельной картой. Открывайте ветви по мере чтения, редактируйте дерево и возвращайтесь к проверяемым источникам.</p></div><div class="hero-actions"><button id="themeLibrary" class="icon-btn" type="button">Светлая тема</button><button id="newMap" class="btn primary" type="button">＋ Новая карта</button></div></div>
    <div class="library-tools"><input id="librarySearch" class="field" type="search" placeholder="Найти карту по названию или описанию" aria-label="Поиск по библиотеке"><label class="check"><input id="showArchived" type="checkbox"> Показывать архив</label></div>
    <div id="mapGrid" class="map-grid" aria-live="polite"></div>
  </section>

  <section id="editor" class="editor hidden" aria-label="Редактор карты мыслей">
    <header class="editor-head"><button id="backLibrary" class="btn ghost back" type="button">← Библиотека</button><div class="map-heading"><strong id="editorTitle">Карта</strong><small id="editorMeta"></small></div><div class="spacer"></div><input id="treeSearch" class="field search" type="search" placeholder="Поиск по узлам /" aria-label="Поиск по узлам"><select id="depthSelect" class="field depth" aria-label="Глубина дерева"><option value="0">Все уровни</option><option value="2">2 уровня</option><option value="3">3 уровня</option><option value="4">4 уровня</option><option value="5">5 уровней</option></select><button id="expandAll" class="icon-btn" type="button">Раскрыть</button><button id="collapseAll" class="icon-btn" type="button">Свернуть</button><button id="mapSettings" class="icon-btn" type="button" aria-label="Настройки карты">⋯</button><button id="themeEditor" class="icon-btn" type="button" aria-label="Переключить тему">☼</button></header>
    <div class="workspace"><main id="canvas" class="canvas" tabindex="0"><div class="canvas-hint">Щелчок — сведения · двойной щелчок — свернуть ветвь · перетащите узел на нового родителя</div><div id="scene" class="scene"><svg id="links" class="links" aria-hidden="true"></svg><div id="tree" class="mind-tree"></div></div><div class="zoom"><button id="zoomOut" class="icon-btn" type="button">−</button><button id="zoomFit" class="icon-btn" type="button">Вписать</button><button id="zoomIn" class="icon-btn" type="button">＋</button></div></main>
      <aside class="inspector" aria-label="Сведения об узле"><div id="inspectorHead" class="inspector-head"><div class="eyebrow">Сведения</div><h2>Выберите узел</h2><div class="muted">Здесь появятся содержание, источники и история.</div></div><div id="tabs" class="tabs hidden"><button class="tab active" data-tab="content">Содержание</button><button class="tab" data-tab="sources">Источники</button><button class="tab" data-tab="history">История</button></div><div id="inspectorBody" class="tab-pane"><div class="welcome"><strong>Спокойный режим чтения</strong>Раскрывайте только нужные ветви. Все подписи всегда остаются видимыми.</div></div></aside>
    </div>
  </section>
</div>

<dialog id="mapDialog"><form id="mapForm"><div class="dialog-head"><div class="eyebrow" id="mapDialogEyebrow">Новая карта</div><h2 id="mapDialogTitle">Создать пустую карту</h2></div><div class="dialog-body"><label>Название<input id="mapTitleInput" class="field" required maxlength="512" autocomplete="off"></label><label>Описание<textarea id="mapDescriptionInput" class="field" maxlength="65536" placeholder="Для чего нужна эта карта"></textarea></label></div><div class="dialog-actions"><button class="btn" value="cancel" formmethod="dialog" type="button" data-close-dialog>Отмена</button><button id="mapSubmit" class="btn primary" type="submit">Создать</button></div></form></dialog>
<dialog id="deleteDialog"><form id="deleteForm"><div class="dialog-head"><div class="eyebrow">Безопасное удаление</div><h2>Что сделать с ветвью?</h2></div><div class="dialog-body"><p id="deleteText" class="muted"></p><label class="check"><input name="deleteMode" type="radio" value="branch" checked> Удалить узел вместе со всей ветвью</label><label class="check"><input name="deleteMode" type="radio" value="promote_children"> Удалить только узел, а дочерние поднять на уровень выше</label></div><div class="dialog-actions"><button class="btn" type="button" data-close-dialog>Отмена</button><button class="btn danger" type="submit">Удалить</button></div></form></dialog>
<div id="toast" class="toast" role="status" aria-live="polite"></div>
<script>
'use strict';
const bootstrap=__MEM_BOOTSTRAP__;
const $=id=>document.getElementById(id), library=$('library'),editor=$('editor'),grid=$('mapGrid'),tree=$('tree'),scene=$('scene'),links=$('links'),inspectorHead=$('inspectorHead'),inspectorBody=$('inspectorBody'),tabs=$('tabs'),toast=$('toast');
let maps=[],doc=null,selectedNodeID='',activeTab='content',collapsed=new Set(),zoom=1,mapDialogMode='create',mapDialogMap=null,dragNodeID='',toastTimer=0;
const kindColor={topic:'#8c7cff',subtopic:'#65d6b4',fact:'#56b8ff',note:'#ffc857',quote:'#d48cff',question:'#ff7f96',task:'#ff9d57',decision:'#43d6c5',link:'#7eb5ff'};
const kindLabel=Object.fromEntries(bootstrap.node_kinds.map(item=>[item.value,item.label]));
function showToast(message,error=false){clearTimeout(toastTimer);toast.textContent=message;toast.className='toast show'+(error?' error':'');toastTimer=setTimeout(()=>toast.className='toast',3200)}
async function api(path,payload={}){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Mem-Session':bootstrap.session_token},body:JSON.stringify(payload)});if(!response.ok){const message=(await response.text()).trim()||'Операция не выполнена';if(response.status===403)throw new Error('Сессия редактора завершена. Перезапустите mem mindmap open.');if(response.status===409&&doc){await loadMap(doc.map.id,false);throw new Error(message+' Карта уже обновлена. Показана свежая версия.')}throw new Error(message)}return response.json()}
function fmtDate(value){try{return new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return value}}
function ruCount(value,one,few,many){const n=Math.abs(Number(value))%100,last=n%10;return value+' '+(n>10&&n<20?many:last===1?one:last>=2&&last<=4?few:many)}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('mem-mindmap-theme',theme);$('themeLibrary').textContent=theme==='dark'?'Светлая тема':'Тёмная тема';$('themeEditor').textContent=theme==='dark'?'☼':'☾'}
function toggleTheme(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')}
applyTheme(localStorage.getItem('mem-mindmap-theme')||'dark');
async function refreshMaps(){try{maps=await api('/api/maps/list',{include_archived:$('showArchived').checked});renderLibrary();const wanted=new URLSearchParams(location.hash.replace(/^#/,'')).get('map');if(wanted&&!doc)await loadMap(wanted,false)}catch(error){showToast(error.message,true);grid.innerHTML='<div class="empty">Не удалось загрузить библиотеку.</div>'}}
function renderLibrary(){const query=$('librarySearch').value.trim().toLocaleLowerCase('ru');grid.textContent='';const shown=maps.filter(item=>!query||(item.title+' '+item.description).toLocaleLowerCase('ru').includes(query));if(!shown.length){const empty=document.createElement('div');empty.className='empty';empty.textContent=maps.length?'По этому запросу карт нет.':'Карт пока нет. Создайте первую пустую карту.';grid.append(empty);return}for(const item of shown){const card=document.createElement('article');card.className='map-card'+(item.status==='archived'?' archived':'');const eyebrow=document.createElement('div');eyebrow.className='eyebrow';eyebrow.textContent=item.mode==='generated'?'Создано моделью':item.mode==='hybrid'?'Совместная работа':'Ручная карта';const title=document.createElement('h2');title.textContent=item.title;const description=document.createElement('p');description.textContent=item.description||'Описание пока не добавлено.';const meta=document.createElement('div');meta.className='map-meta';for(const text of[ruCount(item.node_count,'узел','узла','узлов'),ruCount(item.source_count,'источник','источника','источников'),'ревизия '+item.revision,item.status==='archived'?'архив':'обновлено '+fmtDate(item.updated)]){const pill=document.createElement('span');pill.className='pill';pill.textContent=text;meta.append(pill)}const actions=document.createElement('div');actions.className='card-actions';actions.append(actionButton('Открыть','primary',()=>loadMap(item.id,true)),actionButton('Изменить','',()=>openMapDialog('edit',item)),actionButton('Копия','',()=>openMapDialog('duplicate',item)),actionButton(item.status==='archived'?'Вернуть':'В архив','',()=>setMapStatus(item,item.status==='archived'?'draft':'archived')));card.append(eyebrow,title,description,meta,actions);grid.append(card)}}
function actionButton(label,style,handler){const button=document.createElement('button');button.type='button';button.className='btn small '+style;button.textContent=label;button.addEventListener('click',handler);return button}
function openMapDialog(mode,item=null){mapDialogMode=mode;mapDialogMap=item;$('mapDialogEyebrow').textContent=mode==='create'?'Новая карта':mode==='duplicate'?'Независимая копия':'Параметры карты';$('mapDialogTitle').textContent=mode==='create'?'Создать пустую карту':mode==='duplicate'?'Скопировать карту':'Изменить карту';$('mapSubmit').textContent=mode==='create'?'Создать':mode==='duplicate'?'Создать копию':'Сохранить';$('mapTitleInput').value=mode==='duplicate'?(item.title+' — копия'):(item?.title||'');$('mapDescriptionInput').value=item?.description||'';$('mapDialog').showModal();setTimeout(()=>$('mapTitleInput').focus(),0)}
async function setMapStatus(item,status){try{await api('/api/maps/edit',{map_id:item.id,expected_revision:item.revision,status});showToast(status==='archived'?'Карта помещена в архив.':'Карта возвращена в библиотеку.');await refreshMaps()}catch(error){showToast(error.message,true)}}
$('mapForm').addEventListener('submit',async event=>{event.preventDefault();const title=$('mapTitleInput').value.trim(),description=$('mapDescriptionInput').value.trim();if(!title)return;try{let result;if(mapDialogMode==='create')result=await api('/api/maps/create',{title,description});else if(mapDialogMode==='duplicate')result=await api('/api/maps/duplicate',{map_id:mapDialogMap.id,title});else result=await api('/api/maps/edit',{map_id:mapDialogMap.id,expected_revision:mapDialogMap.revision,title,description});$('mapDialog').close();showToast(mapDialogMode==='duplicate'?'Копия создана.':mapDialogMode==='edit'?'Карта обновлена.':'Карта создана.');await refreshMaps();if(mapDialogMode==='create'||mapDialogMode==='duplicate')await loadMap(result.map.id,true);else if(doc?.map.id===result.map.id){doc=result;renderEditor()}}catch(error){showToast(error.message,true)}});
for(const button of document.querySelectorAll('[data-close-dialog]'))button.addEventListener('click',()=>button.closest('dialog').close());
async function loadMap(id,push=true){try{doc=await api('/api/maps/load',{map_id:id});selectedNodeID=doc.map.root_node_id;collapsed=new Set(JSON.parse(localStorage.getItem('mem-mindmap-collapsed-'+doc.map.id)||'[]'));library.classList.add('hidden');editor.classList.remove('hidden');if(push)history.pushState({map:id},'',location.pathname+'#map='+encodeURIComponent(id));renderEditor()}catch(error){showToast(error.message,true)}}
function backToLibrary(push=true){doc=null;selectedNodeID='';editor.classList.add('hidden');library.classList.remove('hidden');if(push)history.pushState({},'',location.pathname);refreshMaps()}
window.addEventListener('popstate',()=>{const id=new URLSearchParams(location.hash.replace(/^#/,'')).get('map');if(id)loadMap(id,false);else backToLibrary(false)});
function renderEditor(){if(!doc)return;$('editorTitle').textContent=doc.map.title;$('editorMeta').textContent=ruCount(doc.nodes.length,'узел','узла','узлов')+' · ревизия '+doc.map.revision;renderTree();renderInspector()}
function nodeByID(id){return doc?.nodes.find(node=>node.id===id)}
function childrenMap(){const result=new Map;for(const node of doc.nodes){if(!result.has(node.parent_id))result.set(node.parent_id,[]);result.get(node.parent_id).push(node)}for(const items of result.values())items.sort((a,b)=>a.position-b.position||a.label.localeCompare(b.label,'ru'));return result}
function renderTree(){tree.textContent='';links.textContent='';if(!doc)return;const children=childrenMap(),query=$('treeSearch').value.trim().toLocaleLowerCase('ru'),maxDepth=Number($('depthSelect').value),matches=new Set;if(query){for(const node of doc.nodes)if((node.label+' '+node.summary+' '+node.body_markdown).toLocaleLowerCase('ru').includes(query)){let cursor=node;while(cursor){matches.add(cursor.id);cursor=nodeByID(cursor.parent_id)}}}const root=nodeByID(doc.map.root_node_id);if(root)tree.append(buildBranch(root,children,0,query,matches,maxDepth));requestAnimationFrame(()=>{drawLines();focusSelected(false)})}
function buildBranch(node,children,depth,query,matches,maxDepth){const branch=document.createElement('div');branch.className='branch';const shell=document.createElement('div');shell.className='node-shell';const button=document.createElement('button');button.type='button';button.className='node'+(node.id===selectedNodeID?' selected':'')+(query&&!matches.has(node.id)?' dim':'');button.dataset.nodeId=node.id;button.dataset.parentId=node.parent_id;button.style.setProperty('--kind',kindColor[node.kind]||kindColor.subtopic);button.draggable=node.id!==doc.map.root_node_id;const label=document.createElement('span');label.className='node-label';label.textContent=node.label;button.append(label);if(node.summary){const summary=document.createElement('span');summary.className='node-summary';summary.textContent=node.summary;button.append(summary)}const type=document.createElement('span');type.className='node-type';type.textContent=kindLabel[node.kind]||node.kind;button.append(type);if(node.locked){const lock=document.createElement('span');lock.className='lock';lock.textContent='◆';lock.title='Узел закреплён';button.append(lock)}button.addEventListener('click',()=>selectNode(node.id));button.addEventListener('dblclick',event=>{event.preventDefault();toggleCollapsed(node.id)});button.addEventListener('dragstart',event=>{dragNodeID=node.id;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',node.id)});button.addEventListener('dragover',event=>{if(dragNodeID&&dragNodeID!==node.id){event.preventDefault();button.classList.add('drop-target')}});button.addEventListener('dragleave',()=>button.classList.remove('drop-target'));button.addEventListener('drop',async event=>{event.preventDefault();button.classList.remove('drop-target');const moving=event.dataTransfer.getData('text/plain')||dragNodeID;dragNodeID='';if(moving&&moving!==node.id)await moveNode(moving,node.id,-1)});button.addEventListener('dragend',()=>{dragNodeID='';document.querySelectorAll('.drop-target').forEach(item=>item.classList.remove('drop-target'))});shell.append(button);const kids=children.get(node.id)||[],depthLimited=maxDepth>0&&depth+1>=maxDepth,isCollapsed=query?false:(collapsed.has(node.id)||depthLimited);if(kids.length){const collapse=document.createElement('button');collapse.type='button';collapse.className='collapse';collapse.textContent=isCollapsed?String(kids.length):'−';collapse.title=isCollapsed?'Раскрыть ветвь':'Свернуть ветвь';collapse.addEventListener('click',event=>{event.stopPropagation();toggleCollapsed(node.id)});shell.append(collapse)}branch.append(shell);if(kids.length&&!isCollapsed){const wrap=document.createElement('div');wrap.className='children';for(const child of kids){if(query&&!subtreeHasMatch(child,children,matches))continue;wrap.append(buildBranch(child,children,depth+1,query,matches,maxDepth))}if(wrap.children.length)branch.append(wrap)}return branch}
function subtreeHasMatch(node,children,matches){if(matches.has(node.id))return true;return(children.get(node.id)||[]).some(child=>subtreeHasMatch(child,children,matches))}
function drawLines(){links.textContent='';links.setAttribute('width',scene.scrollWidth);links.setAttribute('height',scene.scrollHeight);const sceneRect=scene.getBoundingClientRect();for(const child of tree.querySelectorAll('.node[data-parent-id]:not([data-parent-id=""])')){const parent=tree.querySelector('.node[data-node-id="'+CSS.escape(child.dataset.parentId)+'"]');if(!parent)continue;const a=parent.getBoundingClientRect(),b=child.getBoundingClientRect(),x1=(a.right-sceneRect.left)/zoom,y1=(a.top+a.height/2-sceneRect.top)/zoom,x2=(b.left-sceneRect.left)/zoom,y2=(b.top+b.height/2-sceneRect.top)/zoom,mid=(x1+x2)/2,path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M '+x1+' '+y1+' C '+mid+' '+y1+', '+mid+' '+y2+', '+x2+' '+y2);path.setAttribute('fill','none');path.setAttribute('stroke',kindColor[nodeByID(child.dataset.nodeId)?.kind]||'#66758b');path.setAttribute('stroke-width','2');path.setAttribute('opacity','.72');links.append(path)}}
function selectNode(id){selectedNodeID=id;tree.querySelectorAll('.node').forEach(item=>item.classList.toggle('selected',item.dataset.nodeId===id));renderInspector();focusSelected(false)}
function focusSelected(smooth=true){const el=tree.querySelector('.node[data-node-id="'+CSS.escape(selectedNodeID)+'"]');if(el&&window.innerWidth>900)el.scrollIntoView({block:'nearest',inline:'nearest',behavior:smooth?'smooth':'auto'})}
function toggleCollapsed(id){collapsed.has(id)?collapsed.delete(id):collapsed.add(id);persistCollapsed();renderTree()}
function persistCollapsed(){if(doc)localStorage.setItem('mem-mindmap-collapsed-'+doc.map.id,JSON.stringify([...collapsed]))}
function renderInspector(){const node=nodeByID(selectedNodeID);if(!node){tabs.classList.add('hidden');inspectorBody.innerHTML='<div class="welcome"><strong>Выберите узел</strong>Откройте содержание и источники одним щелчком.</div>';return}tabs.classList.remove('hidden');inspectorHead.innerHTML='';const eyebrow=document.createElement('div');eyebrow.className='eyebrow';eyebrow.textContent=kindLabel[node.kind]||node.kind;const h=document.createElement('h2');h.textContent=node.label;const meta=document.createElement('div');meta.className='muted';meta.textContent=(node.origin==='generated'?'Создан моделью':'Ручной узел')+(node.locked?' · закреплён':'');inspectorHead.append(eyebrow,h,meta);for(const tab of tabs.querySelectorAll('.tab'))tab.classList.toggle('active',tab.dataset.tab===activeTab);if(activeTab==='content')renderContent(node);else if(activeTab==='sources')renderSources(node);else renderHistory()}
function renderContent(node){inspectorBody.textContent='';const form=document.createElement('form');form.className='form-grid';form.innerHTML='<label>Название<input class="field" name="label" maxlength="512" required></label><label>Тип<select class="field" name="kind"></select></label><label>Краткое описание<input class="field" name="summary" maxlength="65536"></label><label>Текст узла<textarea class="field" name="body" maxlength="65536" placeholder="Подробности, заметки или пояснение"></textarea></label><label class="check"><input name="locked" type="checkbox"> Закрепить от случайного изменения</label><div class="actions"><button class="btn primary" type="submit">Сохранить</button><button class="btn" type="button" data-add-child>＋ Дочерний</button><button class="btn" type="button" data-add-sibling>＋ Соседний</button><button class="btn danger" type="button" data-delete>Удалить</button></div>';form.elements.label.value=node.label;form.elements.summary.value=node.summary||'';form.elements.body.value=node.body_markdown||'';form.elements.locked.checked=Boolean(node.locked);for(const item of bootstrap.node_kinds){const option=document.createElement('option');option.value=item.value;option.textContent=item.label;option.selected=node.kind===item.value;form.elements.kind.append(option)}form.addEventListener('submit',event=>{event.preventDefault();saveNode(node,form)});form.querySelector('[data-add-child]').addEventListener('click',()=>showNewNodeForm(node.id));const sibling=form.querySelector('[data-add-sibling]');sibling.disabled=!node.parent_id;sibling.addEventListener('click',()=>showNewNodeForm(node.parent_id,node.position+1));const del=form.querySelector('[data-delete]');del.disabled=node.id===doc.map.root_node_id;del.addEventListener('click',()=>openDelete(node));inspectorBody.append(form,buildMoveSection(node))}
function showNewNodeForm(parentID,position=-1){const parent=nodeByID(parentID);inspectorBody.textContent='';const wrap=document.createElement('div');wrap.className='form-grid';wrap.innerHTML='<div class="eyebrow">Новый узел</div><h2></h2><label>Название<input class="field" name="label" maxlength="512" required autofocus></label><label>Тип<select class="field" name="kind"></select></label><label>Краткое описание<input class="field" name="summary" maxlength="65536"></label><label>Текст<textarea class="field" name="body" maxlength="65536"></textarea></label><div class="actions"><button class="btn primary" data-save type="button">Добавить</button><button class="btn" data-cancel type="button">Отмена</button></div>';wrap.querySelector('h2').textContent='В ветку «'+parent.label+'»';for(const item of bootstrap.node_kinds){const option=document.createElement('option');option.value=item.value;option.textContent=item.label;wrap.querySelector('[name=kind]').append(option)}wrap.querySelector('[data-save]').addEventListener('click',async()=>{const label=wrap.querySelector('[name=label]').value.trim();if(!label){wrap.querySelector('[name=label]').focus();return}try{const result=await api('/api/nodes/add',{map_id:doc.map.id,parent_id:parentID,label,position,kind:wrap.querySelector('[name=kind]').value,summary:wrap.querySelector('[name=summary]').value.trim(),body_markdown:wrap.querySelector('[name=body]').value,expected_revision:doc.map.revision});doc=result.document;selectedNodeID=result.node.id;collapsed.delete(parentID);persistCollapsed();renderEditor();showToast('Узел добавлен.')}catch(error){showToast(error.message,true)}});wrap.querySelector('[data-cancel]').addEventListener('click',renderInspector);inspectorBody.append(wrap);setTimeout(()=>wrap.querySelector('[name=label]').focus(),0)}
async function saveNode(node,form){try{const result=await api('/api/nodes/edit',{map_id:doc.map.id,node_id:node.id,label:form.elements.label.value.trim(),kind:form.elements.kind.value,summary:form.elements.summary.value.trim(),body_markdown:form.elements.body.value,locked:form.elements.locked.checked,expected_revision:doc.map.revision});doc=result.document;selectedNodeID=result.node.id;renderEditor();showToast('Изменения сохранены.')}catch(error){showToast(error.message,true)}}
function buildMoveSection(node){const section=document.createElement('div');section.className='section form-grid';const title=document.createElement('div');title.className='eyebrow';title.textContent='Положение в дереве';const parent=document.createElement('select');parent.className='field';for(const candidate of doc.nodes){if(candidate.id===node.id||isDescendant(node.id,candidate.id))continue;const option=document.createElement('option');option.value=candidate.id;option.textContent=candidate.label;option.selected=candidate.id===node.parent_id;parent.append(option)}const position=document.createElement('input');position.className='field';position.type='number';position.min='0';position.value=String(node.position);const button=document.createElement('button');button.className='btn';button.type='button';button.textContent='Переместить';button.disabled=node.id===doc.map.root_node_id;button.addEventListener('click',()=>moveNode(node.id,parent.value,Number(position.value)));section.append(title,parent,position,button);return section}
function isDescendant(ancestorID,candidateID){let cursor=nodeByID(candidateID);while(cursor?.parent_id){if(cursor.parent_id===ancestorID)return true;cursor=nodeByID(cursor.parent_id)}return false}
async function moveNode(nodeID,parentID,position){try{const result=await api('/api/nodes/move',{map_id:doc.map.id,node_id:nodeID,parent_id:parentID,position,expected_revision:doc.map.revision});doc=result.document;selectedNodeID=result.node.id;collapsed.delete(parentID);persistCollapsed();renderEditor();showToast('Узел перемещён.')}catch(error){showToast(error.message,true)}}
function openDelete(node){$('deleteText').textContent='Узел «'+node.label+'». Операцию можно отменить через вкладку «История».';$('deleteDialog').dataset.nodeId=node.id;$('deleteDialog').showModal()}
$('deleteForm').addEventListener('submit',async event=>{event.preventDefault();const dialog=$('deleteDialog'),nodeID=dialog.dataset.nodeId,mode=new FormData(event.currentTarget).get('deleteMode');try{doc=await api('/api/nodes/delete',{map_id:doc.map.id,node_id:nodeID,mode,expected_revision:doc.map.revision});selectedNodeID=doc.map.root_node_id;dialog.close();renderEditor();showToast('Узел удалён. Изменение доступно для отмены.')}catch(error){showToast(error.message,true)}});
function renderSources(node){inspectorBody.textContent='';if(!node.sources.length){const empty=document.createElement('div');empty.className='welcome';empty.innerHTML='<strong>Источников пока нет</strong>На этапе 1.61 здесь появится поиск и привязка фрагментов. Уже добавленные через CLI источники отображаются полностью.';inspectorBody.append(empty);return}for(const source of node.sources){const card=document.createElement('article');card.className='source-card';const title=document.createElement('strong');title.textContent=source.title||source.evidence?.source_path||source.url||'Источник';const locator=document.createElement('div');locator.className='muted';locator.textContent=source.locator||humanEvidenceLocator(source.evidence);card.append(title,locator);if(source.evidence_state){const state=document.createElement('div');state.className='state-'+source.evidence_state;state.textContent=source.evidence_state==='current'?'Источник актуален':source.evidence_state==='stale'?'Источник изменился':'Источник отсутствует';card.append(state)}const excerpt=source.evidence?.excerpt;if(excerpt){const pre=document.createElement('pre');pre.textContent=excerpt;card.append(pre)}if(source.url){const link=document.createElement('a');link.href=source.url;link.target='_blank';link.rel='noreferrer';link.textContent='Открыть ссылку';card.append(link)}inspectorBody.append(card)}}
function humanEvidenceLocator(e){if(!e)return'';const parts=[];if(e.page)parts.push('страница '+e.page);if(e.block_index)parts.push('блок '+e.block_index);if(e.block_chunk_index)parts.push('фрагмент '+e.block_chunk_index);return parts.join(' · ')}
async function renderHistory(){inspectorBody.innerHTML='<div class="muted">Загружаю историю…</div>';try{const[changes,snapshots]=await Promise.all([api('/api/history/list',{map_id:doc.map.id,limit:40}),api('/api/snapshots/list',{map_id:doc.map.id,limit:12})]);inspectorBody.textContent='';const actions=document.createElement('div');actions.className='actions section';const undo=actionButton('↶ Отменить последнее','',async()=>{try{const result=await api('/api/history/undo',{map_id:doc.map.id,change_id:0,expected_revision:doc.map.revision});doc=result.document;selectedNodeID=doc.map.root_node_id;renderEditor();activeTab='history';renderInspector();showToast('Последнее изменение отменено.')}catch(error){showToast(error.message,true)}});undo.disabled=!changes.some(item=>item.action!=='create_map'&&!item.action.startsWith('undo:'));const redo=actionButton('↷ Повторить','',async()=>{try{const result=await api('/api/history/redo',{map_id:doc.map.id,change_id:0,expected_revision:doc.map.revision});doc=result.document;selectedNodeID=doc.map.root_node_id;renderEditor();activeTab='history';renderInspector();showToast('Отменённое изменение повторено.')}catch(error){showToast(error.message,true)}});redo.disabled=!changes.some(item=>item.action.startsWith('undo:')&&!changes.some(other=>other.reverts_change_id===item.id));const snapshot=actionButton('◇ Контрольная точка','',async()=>{const reason='Ручная точка · '+new Date().toLocaleString('ru-RU');try{await api('/api/snapshots/create',{map_id:doc.map.id,reason,expected_revision:doc.map.revision});showToast('Контрольная точка создана.');renderHistory()}catch(error){showToast(error.message,true)}});actions.append(undo,redo,snapshot);inspectorBody.append(actions);const snapshotTitle=document.createElement('div');snapshotTitle.className='eyebrow section';snapshotTitle.textContent='Контрольные точки · '+snapshots.length;inspectorBody.append(snapshotTitle);for(const item of changes){const card=document.createElement('article');card.className='history-card';const strong=document.createElement('strong');strong.textContent=humanAction(item.action);const meta=document.createElement('div');meta.className='muted';meta.textContent='ревизия '+item.new_revision+' · '+fmtDate(item.created);card.append(strong,meta);if(item.comment){const comment=document.createElement('div');comment.textContent=item.comment;card.append(comment)}inspectorBody.append(card)}}catch(error){inspectorBody.textContent=error.message;showToast(error.message,true)}}
function humanAction(action){const labels={create_map:'Карта создана',edit_map:'Параметры карты изменены',add_node:'Узел добавлен',edit_node:'Узел изменён',move_node:'Узел перемещён',attach_evidence:'Источник привязан','delete_node:branch':'Ветвь удалена','delete_node:promote_children':'Узел удалён, дочерние подняты'};if(action.startsWith('undo:'))return'Отменено: '+humanAction(action.slice(5));if(action.startsWith('redo:'))return'Повторено: '+humanAction(action.slice(5));return labels[action]||action}
for(const tab of tabs.querySelectorAll('.tab'))tab.addEventListener('click',()=>{activeTab=tab.dataset.tab;renderInspector()});
function setZoom(value){zoom=Math.max(.55,Math.min(1.6,value));scene.style.transform='scale('+zoom+')';scene.style.marginRight=((zoom-1)*scene.scrollWidth)+'px';scene.style.marginBottom=((zoom-1)*scene.scrollHeight)+'px';requestAnimationFrame(drawLines)}
function fitTree(){const canvas=$('canvas'),width=Math.max(1,tree.scrollWidth+220),height=Math.max(1,tree.scrollHeight+160);setZoom(Math.min(1,(canvas.clientWidth-30)/width,(canvas.clientHeight-30)/height));canvas.scrollTo({left:0,top:0,behavior:'smooth'})}
$('zoomOut').addEventListener('click',()=>setZoom(zoom-.1));$('zoomIn').addEventListener('click',()=>setZoom(zoom+.1));$('zoomFit').addEventListener('click',fitTree);
$('expandAll').addEventListener('click',()=>{collapsed.clear();persistCollapsed();$('depthSelect').value='0';renderTree()});$('collapseAll').addEventListener('click',()=>{collapsed=new Set(doc.nodes.filter(node=>node.id!==doc.map.root_node_id).map(node=>node.id));collapsed.add(doc.map.root_node_id);persistCollapsed();renderTree()});
$('treeSearch').addEventListener('input',renderTree);$('depthSelect').addEventListener('change',renderTree);$('librarySearch').addEventListener('input',renderLibrary);$('showArchived').addEventListener('change',refreshMaps);$('newMap').addEventListener('click',()=>openMapDialog('create'));$('backLibrary').addEventListener('click',()=>backToLibrary(true));$('mapSettings').addEventListener('click',()=>openMapDialog('edit',doc.map));$('themeLibrary').addEventListener('click',toggleTheme);$('themeEditor').addEventListener('click',toggleTheme);
window.addEventListener('resize',()=>requestAnimationFrame(drawLines));new ResizeObserver(()=>requestAnimationFrame(drawLines)).observe(tree);
document.addEventListener('keydown',event=>{if(event.key==='/'&&document.activeElement.tagName!=='INPUT'&&document.activeElement.tagName!=='TEXTAREA'){event.preventDefault();(doc?$('treeSearch'):$('librarySearch')).focus()}if(event.key==='Insert'&&doc&&selectedNodeID){event.preventDefault();activeTab='content';renderInspector();showNewNodeForm(selectedNodeID)}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'&&doc&&activeTab==='content'){const form=inspectorBody.querySelector('form');if(form){event.preventDefault();form.requestSubmit()}}});
refreshMaps();
</script>
</body>
</html>`
